# Form implementation generated from reading ui file '.\ui\addlk.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Add_lk_form(object):
    def setupUi(self, Add_lk_form):
        Add_lk_form.setObjectName("Add_lk_form")
        Add_lk_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Add_lk_form.resize(691, 646)
        self.verticalLayout = QtWidgets.QVBoxLayout(Add_lk_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(parent=Add_lk_form)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label)
        self.TlgLineEdit = QtWidgets.QLineEdit(parent=Add_lk_form)
        self.TlgLineEdit.setObjectName("TlgLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.TlgLineEdit)
        self.Label_2 = QtWidgets.QLabel(parent=Add_lk_form)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_2)
        self.TlgDateEdit = QtWidgets.QDateEdit(parent=Add_lk_form)
        self.TlgDateEdit.setCalendarPopup(True)
        self.TlgDateEdit.setObjectName("TlgDateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.TlgDateEdit)
        self.Label_3 = QtWidgets.QLabel(parent=Add_lk_form)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_3)
        self.Label_4 = QtWidgets.QLabel(parent=Add_lk_form)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_4)
        self.textEdit = QtWidgets.QTextEdit(parent=Add_lk_form)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit)
        self.Label_5 = QtWidgets.QLabel(parent=Add_lk_form)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_5)
        self.LkLineEdit = QtWidgets.QLineEdit(parent=Add_lk_form)
        self.LkLineEdit.setObjectName("LkLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LkLineEdit)
        self.SrokDateEdit = QtWidgets.QDateEdit(parent=Add_lk_form)
        self.SrokDateEdit.setCalendarPopup(True)
        self.SrokDateEdit.setObjectName("SrokDateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SrokDateEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.SpecLayout = QtWidgets.QHBoxLayout()
        self.SpecLayout.setObjectName("SpecLayout")
        self.verticalLayout.addLayout(self.SpecLayout)
        self.selectorLayout = QtWidgets.QHBoxLayout()
        self.selectorLayout.setObjectName("selectorLayout")
        self.verticalLayout.addLayout(self.selectorLayout)
        self.planesLayout = QtWidgets.QHBoxLayout()
        self.planesLayout.setObjectName("planesLayout")
        self.verticalLayout.addLayout(self.planesLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(parent=Add_lk_form)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=Add_lk_form)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Add_lk_form)
        QtCore.QMetaObject.connectSlotsByName(Add_lk_form)

    def retranslateUi(self, Add_lk_form):
        _translate = QtCore.QCoreApplication.translate
        Add_lk_form.setWindowTitle(_translate("Add_lk_form", "Добавить"))
        self.Label.setText(_translate("Add_lk_form", "Номер казания/ТЛГ"))
        self.Label_2.setText(_translate("Add_lk_form", "Дата указания/ТЛГ"))
        self.Label_3.setText(_translate("Add_lk_form", "Срок выполнения"))
        self.Label_4.setText(_translate("Add_lk_form", "Краткое описание"))
        self.Label_5.setText(_translate("Add_lk_form", "Номер ЛК"))
        self.add_btn.setText(_translate("Add_lk_form", "Добавить"))
        self.cancel_btn.setText(_translate("Add_lk_form", "Отмена"))
